vesrion: "3"

services:
  algoserver.api:
    #image: $REGISTRY/algoserver:latest
    build: .
    container_name: algoserver.api
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    networks:
      - internal
    ports:
      - "5013:80"
    environment:
      - Logging:LogLevel:Default=Debug
      - AllowedHosts=*
      - ASPNETCORE_ENVIRONMENT=Staging
      - Authority=$IDENTITY_AUTHORITY
      - RoutePrefix=algoserver
      - DatafeedEndpoint=https://$DATAFEED_HOST
    
  algostatistics:
    image: mysql:8.0.13
    container_name: algostatistics
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    networks:
      - internal
    volumes:
      - /data/algostatistics:/var/lib/mysql
    #  - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: algostatistics
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    labels:
      - "com.centurylinklabs.watchtower.enable=false"